# return sing in view with html form
GET http://localhost:3000/auth?client_id=Axra123 HTTP/1.1

####

# function - create user account for axra 
# return - created user data
POST http://localhost:3000/auth/signup HTTP/1.1
Content-Type: application/json

{
    "username": "axra",
    "email": "axra@gmail.com",
    "phone": "0911111111",
    "password": "111111"
}

####

# function - login user 
# return - Authentication code for generate token but this code will be one time used. 
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "client_id": "Axra123",
    "email" : "axra@gmail.com",
    "password" : "111111"
}

###

#function - generate token 
#return - token
@token = 7542e13a74fd18abc912807c6acc3eef
GET http://localhost:3000/auth/token?code={{token}} HTTP/1.1

####
@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImF4cmFAZ21haWwuY29tIiwiaWF0IjoxNzA1MzI4MjIxLCJleHAiOjE3MDU5MzMwMjF9.4ceZjVhTbTX4JUjVbG5bm8v25AQdAD362VEf_1nKMRk

POST http://localhost:3000/auth/refresh HTTP/1.1
Cookie: jwt={{refreshToken}}


